server:
  port: 9000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.10
  application:
    name: api-passenger
  redis:
    port: 6379
    host: 192.168.1.10
    database: 0
